### ISSUE TITLE
YAML configuration needs to be camelcase

### ISSUE THREAD

**Issue by jcheroske** [DeFacto-Team/Factom-Open-API#3]
The `/config/config.yaml` file is all lowercase. The keys should be camelcase.

**Comment by ilzheev** [comment]
I haven't found any specification for using camelcase in YAML files.
Instead, I found a recommendation to use the same style of naming, as used in app.

https://stackoverflow.com/questions/22771226/what-is-the-canonical-yaml-naming-style
```
Use the standard dictated by the surrounding software.

For example, in my current project the YAML file contains default values for Python attributes. Since the names used in YAML appear in the associated Python API, it is clear that on this particular project, the YAML names should obey the Python lower_case_with_underscores naming convention per PEP-8.
```

As app is Golang, I suggest to use Go's naming style.

```yaml
LogLevel: 6
GZipLevel: -1
API:
  HTTPPort: 8081
  Logging: true
Store:
  Host: "localhost"
  Port: 5433
  User: "postgres"
  Password: "postgres"
  DBName: "postgres"
Factom:
  URL: "https://api.factomd.net"
  User: ""
  Password: ""
  EsAddress: ""
```
